let selectStt = document.querySelector('#slcst');
let fontDiv = document.querySelector('#fontLoc');
document.querySelector('#fontPage').addEventListener('click', function() {
  if(selectStt.value === 'AC')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'AL')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'AP')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'AM')
  fontDiv.innerHTML = 'Fontes:<br>http://www.brasil-turismo.com/amazonas.htm<br>https://www.acritica.com/channels/cotidiano/news/rede-de-observadores-criada-ha-cinco-anos-reune-pessoas-que-observam-passaros<br>https://www.suapesquisa.com/fauna_flora/amazonas.htm<br>http://meioambiente.culturamix.com/natureza/o-clima-da-amazonia<br>https://estudandoabiologia.wordpress.com/2012/11/06/onca-pintada/<br>https://www.youtube.com/watch?v=5b4zeWOyOY4<br>http://meioambiente.culturamix.com/ecologia/recursos-naturais-da-amazonia';
  if(selectStt.value === 'BA')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'CE')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'ES')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'GO')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'MA')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'MT')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'MS')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'MG')
  fontDiv.innerHTML = 'Fontes:<br>https://pt.wikipedia.org/wiki/Ficheiro:Tamandu%C3%A1-bandeira_com_filhote_em_pastagem_-_cropped.jpg<br>http://www.naturezaterra.com.br/brasil-MG.htm<br>http://meioambiente.culturamix.com/ecologia/fauna/fauna-da-mata-atlantica';
  if(selectStt.value === 'PA')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'PB')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'PR')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'PE')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'PI')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'RJ')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'RN')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'RS')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'RO')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'RR')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
  if(selectStt.value === 'SC')
  fontDiv.innerHTML = 'Fontes:<br>http://geoesporte.blogspot.com/2014/09/aspectos-fisicos-de-santa-catarina-o.html<br>http://faunaeflora.terradagente.g1.globo.com/fauna/aves/NOT,0,0,1223537,Araponga.aspx<br>http://www.faunacps.cnpm.embrapa.br/mamifero/onca_p.html<br>http://www.avescatarinenses.com.br/animais/2-fauna/595-macaco-prego/4045<br>https://www.tripadvisor.com.br/LocationPhotoDirectLink-g303441-d1493739-i209783357-Jardim_Botanico_de_Curitiba-Curitiba_State_of_Parana.html';
  if(selectStt.value === 'SP')
  fontDiv.innerHTML = 'Fontes:<br>http://www.cidadedesaopaulo.com/ecoturismo/bemvindo/fauna-e-flora/<br>https://www.suapesquisa.com/fauna_flora/estado_sao_paulo.htm<br>https://curiosidadeanimalbrasil.wordpress.com/tag/muriqui-do-sul/<br>http://qplantaeessa.blogspot.com/2016/04/flor-de-sao-joao-ou-cipo-de-sao-joao.html#.W5p7KXVKjCI<br>http://regbor.blogspot.com/2010/07/o-ipe-beira-da-estrada.html';
  if(selectStt.value === 'SE')
  fontDiv.innerHTML = 'Fontes:<br>http://br.geoview.info/vegetacao_do_agreste_pernambucanoregiao_de_sao_caetanope,1686679p<br>https://casadospassaros.net/murucutu/<br>http://faunaefloradorn.blogspot.com/2010/10/pintor-verdadeirotangara-fastuosa-fauna.html<br>https://www.csfotojornalismo.net/%C3%81rvores-e-Plantas';
  if(selectStt.value === 'TO')
  fontDiv.innerHTML = 'Fontes:<br>google.com';
});
